// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr3fz7s1JLEcwXYh3pnhpGJfCk53nTkg4',
    appId: '1:1002470893434:web:7979b2287ab61011dd58c3',
    messagingSenderId: '1002470893434',
    projectId: 'ecommerce-2003',
    authDomain: 'ecommerce-2003.firebaseapp.com',
    storageBucket: 'ecommerce-2003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGeWNUWmUXxJCJQAKZnd5h14YAifsiw0o',
    appId: '1:1002470893434:android:d0b14cc21b69d01cdd58c3',
    messagingSenderId: '1002470893434',
    projectId: 'ecommerce-2003',
    storageBucket: 'ecommerce-2003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MrGLM9NK7zyF9U95-DybnMctZwibmVM',
    appId: '1:1002470893434:ios:3039d885688aab98dd58c3',
    messagingSenderId: '1002470893434',
    projectId: 'ecommerce-2003',
    storageBucket: 'ecommerce-2003.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-MrGLM9NK7zyF9U95-DybnMctZwibmVM',
    appId: '1:1002470893434:ios:3039d885688aab98dd58c3',
    messagingSenderId: '1002470893434',
    projectId: 'ecommerce-2003',
    storageBucket: 'ecommerce-2003.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr3fz7s1JLEcwXYh3pnhpGJfCk53nTkg4',
    appId: '1:1002470893434:web:8d49a62d92bdf22ddd58c3',
    messagingSenderId: '1002470893434',
    projectId: 'ecommerce-2003',
    authDomain: 'ecommerce-2003.firebaseapp.com',
    storageBucket: 'ecommerce-2003.appspot.com',
  );
}
